version: "3.9"
services:
  db:
    image: postgres:15
    container_name: happy_report_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: happy_report
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: ./apps/server
    container_name: happy_report_api
    depends_on:
      - db
    environment:
      PORT: 3000
      GAMES_DIR: /games
      PGHOST: db
      PGPORT: 5432
      PGUSER: app
      PGPASSWORD: app
      PGDATABASE: happy_report
      JWT_SECRET: change_me
      ADMIN_REG_SECRET: admin_secret
    ports:
      - "3000:3000"
  client:
    build: ./apps/client
    container_name: finplay_client
    depends_on:
      - db
      - api
    environment:
      DATABASE_URL: postgresql://app:app@db:5432/happy_report
      JWT_SECRET: change_me
    ports:
      - "3001:3001"
    volumes:
      - ./apps/client:/app
      - /app/node_modules
      - /app/.next

volumes:
  pgdata:
